[package]
name = "exsecp256k1"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "exsecp256k1"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
lazy_static = "1.0"
libsecp256k1 = "0.3.5"
rustler = {git = "git://github.com/rusterlium/rustler.git", branch="master"}
